In [1]:
import numpy as np

In [74]:
def smth(x):
    flag = (x == 0)
    flag[-1] = False
    y = x * np.roll(flag, 1)
    print(x)
    print(y)
    y_max = y.max()
    if y_max == 0:
        return 'Wrong list'
    else:
        return y_max

In [75]:
x = np.array([0, 11, 0, 0, -7, 2, 0, 4, 0])
smth(x)

[ 0 11  0  0 -7  2  0  4  0]
[ 0 11  0  0 -7  0  0  4  0]


11

In [76]:
x = np.array([0, 11, 0, 0, -7, 2, 0, 20, 0])
smth(x)

[ 0 11  0  0 -7  2  0 20  0]
[ 0 11  0  0 -7  0  0 20  0]


20

In [77]:
x = np.array([0, 1])
smth(x)

[0 1]
[0 1]


1

In [78]:
x = np.array([1, 0])
smth(x)

[1 0]
[0 0]


'Wrong list'

In [79]:
x = np.array([0, 11, 0, 0, -7, 2, 5, 6, 7, 0, 4, 22])
smth(x)

[ 0 11  0  0 -7  2  5  6  7  0  4 22]
[ 0 11  0  0 -7  0  0  0  0  0  4  0]


11

In [80]:
x = np.array([0, 11, 0, 0, -7, 2, 5, 6, 7, 0, 4, 0, 22])
smth(x)

[ 0 11  0  0 -7  2  5  6  7  0  4  0 22]
[ 0 11  0  0 -7  0  0  0  0  0  4  0 22]


22