In [1]:
import numpy as np

In [14]:
def smth(x):
    flag = x == 0
    return x + np.roll(x, 1) * flag

In [82]:
x = np.array([8, 0, 0, 1, 0, 0, 0, -17.5, 0])
# smth(x)

In [83]:
T_F = x == 0
np.concatenate((x.reshape((9, 1)), np.roll(x, 1).reshape(9, 1)), axis=1)

array([[  8. ,   0. ],
       [  0. ,   8. ],
       [  0. ,   0. ],
       [  1. ,   0. ],
       [  0. ,   1. ],
       [  0. ,   0. ],
       [  0. ,   0. ],
       [-17.5,   0. ],
       [  0. , -17.5]])

In [87]:
base_m = np.repeat(x.reshape(1,9), 9, axis=0)
print(base_m)
print(np.roll(base_m, np.arange(0, 9)))

[[  8.    0.    0.    1.    0.    0.    0.  -17.5   0. ]
 [  8.    0.    0.    1.    0.    0.    0.  -17.5   0. ]
 [  8.    0.    0.    1.    0.    0.    0.  -17.5   0. ]
 [  8.    0.    0.    1.    0.    0.    0.  -17.5   0. ]
 [  8.    0.    0.    1.    0.    0.    0.  -17.5   0. ]
 [  8.    0.    0.    1.    0.    0.    0.  -17.5   0. ]
 [  8.    0.    0.    1.    0.    0.    0.  -17.5   0. ]
 [  8.    0.    0.    1.    0.    0.    0.  -17.5   0. ]
 [  8.    0.    0.    1.    0.    0.    0.  -17.5   0. ]]
[[  8.    0.    0.    1.    0.    0.    0.  -17.5   0. ]
 [  8.    0.    0.    1.    0.    0.    0.  -17.5   0. ]
 [  8.    0.    0.    1.    0.    0.    0.  -17.5   0. ]
 [  8.    0.    0.    1.    0.    0.    0.  -17.5   0. ]
 [  8.    0.    0.    1.    0.    0.    0.  -17.5   0. ]
 [  8.    0.    0.    1.    0.    0.    0.  -17.5   0. ]
 [  8.    0.    0.    1.    0.    0.    0.  -17.5   0. ]
 [  8.    0.    0.    1.    0.    0.    0.  -17.5   0. ]
 [  8.    0.    0.    1.    0.

In [89]:
roll_m = np.roll(np.eye(3), np.arange(0, 3))
print(np.eye(3))
print(roll_m)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]


In [96]:
roll_m = np.roll(np.eye(3), [2])
print(np.eye(3))
print(roll_m)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 1. 1.]
 [0. 0. 0.]
 [1. 0. 0.]]
