In [6]:
import numpy as np

In [14]:
def my_mean(x):
    return np.sum(x, axis=0) / x.shape[0]

In [15]:
def my_cov(x):
    return 1 / x.shape[0] * (x - my_mean(x)).T @ (x - my_mean(x))

In [16]:
x = np.array([[175, 4], [20, 2],  [25, 8]])
print(x)
print(my_mean(x))

[[175   4]
 [ 20   2]
 [ 25   8]]
[73.33333333  4.66666667]


In [17]:
x = np.array([[175, 4], [20, 2],  [25, 8]])
print(x)
print(my_cov(x))

[[175   4]
 [ 20   2]
 [ 25   8]]
[[5172.22222222  -28.88888889]
 [ -28.88888889    6.22222222]]
